---
# Source: demoapp/charts/lambda/templates/lambda-event-source-mapping.yaml
# Source: demoapp/charts/lambda/templates/lambda.yaml
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: EventSourceMapping
metadata:
  name: dev-lambda
  namespace: ack-lambda
  annotations:
    services.k8s.aws/region: us-west-2
spec:
  functionName: dev-lambda
  eventSourceARN: arn:aws:sqs:us-west-2:897729104724:dev-conversion-to-pdf--20250507041644562500000004.fifo
  batchSize: 10
